--v1
SELECT * FROM "@APPROVALSTATUS" WHERE "U_DocEntry" IN (36162, 36163, 36165, 36166, 36168, 36172, 36240, 36241,
36246, 36248);

--v2 Select Approval Details for given DocEntry
SELECT "U_DocEntry", "U_ApproverId", "U_DraftStatus", "U_DateTime"
 FROM "@APPROVALSTATUS"
WHERE "U_DocEntry" IN (36162, 36163, 36165, 36166, 36168, 36172, 36240, 36241, 36246, 36248)
 AND "U_ApproverId" = 95;

--UPDATE
UPDATE "@APPROVALSTATUS" SET "U_DraftStatus" = 'PENDING', "U_DateTime" = NULL
WHERE "U_DocEntry" IN (36162, 36163, 36165, 36166, 36168, 36172, 36240, 36241, 36246, 36248)
 AND "U_ApproverId" = 95; --Navin

--SELECT No. of Approvers for given Draft#
SELECT T0."U_NoOfApprovals" FROM ODRF T0 WHERE T0."DocEntry" IN (36162, 36163, 36165, 36166, 36168, 36172, 36240, 36241, 36246, 36248);

--
UPDATE ODRF SET "U_NoOfApprovals" = 2 WHERE "DocEntry" IN (36162, 36163, 36165, 36166, 36168, 36172, 36240, 36241, 36246, 36248);

--
SELECT T0."ObjType", T0."U_NoOfApprovals" FROM ODRF T0 WHERE T0."U_NoOfApprovals" = 9;

--July22'21
UPDATE "@APPROVALSTATUS" SET "U_DraftStatus" = 'PENDING', "U_DateTime" = NULL
WHERE "U_DocEntry" IN (36752)
 AND "U_ApproverId" = 95;
 

--July30'21
--PENDING STs that have already received the required NO. OF APPROVALs
SELECT T0."U_NoOfApprovals", T0."U_TargetRecDocNum", T0."U_DraftStatus", T0.* FROM ODRF T0
	WHERE T0."DocEntry" IN (36240, 36376, 36243, 36244, 36250, 36251, 36253, 36376, 36390, 36513);
	
--Drafts that were with 9 No. Of Approvals Required
SELECT T0."U_NoOfApprovals", T0."U_TargetRecDocNum", T0."U_DraftStatus", T0.* FROM ODRF T0
	WHERE T0."DocEntry" IN (36243, 36244, 36250, 36251, 36253);
	
--1 Get the status of Navin
SELECT "U_DraftStatus", "U_DateTime"
FROM "@APPROVALSTATUS"
WHERE "U_DocEntry" IN (36243, 36244, 36250, 36251, 36253)
 AND "U_ApproverId" = 95; --Navin
 
--2 v1 Prepare backup of Approval Time
SELECT CONCAT('UPDATE "@APPROVALSTATUS" SET "U_DateTime" = ', CONCAT(TO_CHAR("U_DateTime", 'YYYY-MM-DD HH24:MI:SS.FF2'), CONCAT(' WHERE "U_ApprovalStatusId"= ', "U_ApprovalStatusId")))
FROM "@APPROVALSTATUS"
WHERE "U_DocEntry" IN (36243, 36244, 36250, 36251, 36253)
 AND "U_ApproverId" = 95; --Navin
 
--v2
SELECT CONCAT('UPDATE "@APPROVALSTATUS" SET "U_DateTime" = TO_TIMESTAMP(''', CONCAT(TO_CHAR("U_DateTime", 'YYYY-MM-DD HH24:MI:SS.FF2'), CONCAT(''', ''YYYY-MM-DD HH24:MI:SS.FF2'') WHERE "U_ApprovalStatusId"= ', "U_ApprovalStatusId")))
FROM "@APPROVALSTATUS"
WHERE "U_DocEntry" IN (36243, 36244, 36250, 36251, 36253)
 AND "U_ApproverId" = 95; --Navin
 
--3 Reset Navin's status, so he could approve again for the Service Layer to create a ST
UPDATE "@APPROVALSTATUS" SET "U_DraftStatus" = 'PENDING', "U_DateTime" = NULL
WHERE "U_DocEntry" IN (36243, 36244, 36250, 36251, 36253)
 AND "U_ApproverId" = 95; --Navin

--4 Backup generated by --2. v2 (to restore the original Approval Date/Time)
UPDATE "@APPROVALSTATUS" SET "U_DateTime" = TO_TIMESTAMP('2021-07-17 10:50:54.00', 'YYYY-MM-DD HH24:MI:SS.FF2') WHERE "U_ApprovalStatusId"= 059056573	
UPDATE "@APPROVALSTATUS" SET "U_DateTime" = TO_TIMESTAMP('2021-07-16 16:46:13.00', 'YYYY-MM-DD HH24:MI:SS.FF2') WHERE "U_ApprovalStatusId"= 044769224	
UPDATE "@APPROVALSTATUS" SET "U_DateTime" = TO_TIMESTAMP('2021-07-16 16:46:25.00', 'YYYY-MM-DD HH24:MI:SS.FF2') WHERE "U_ApprovalStatusId"= 606459069	
UPDATE "@APPROVALSTATUS" SET "U_DateTime" = TO_TIMESTAMP('2021-07-17 11:47:39.00', 'YYYY-MM-DD HH24:MI:SS.FF2') WHERE "U_ApprovalStatusId"= 587817956	
UPDATE "@APPROVALSTATUS" SET "U_DateTime" = TO_TIMESTAMP('2021-07-16 14:14:51.00', 'YYYY-MM-DD HH24:MI:SS.FF2') WHERE "U_ApprovalStatusId"= 008154893	
